{"trial_id": "0018", "hyperparameters": {"space": [{"class_name": "Choice", "config": {"name": "activation", "default": "relu", "conditions": [], "values": ["relu", "tanh", "sigmoid"], "ordered": false}}, {"class_name": "Int", "config": {"name": "first_units", "default": null, "conditions": [], "min_value": 1, "max_value": 10, "step": 2, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "num_layers", "default": null, "conditions": [], "min_value": 1, "max_value": 6, "step": 1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_0", "default": null, "conditions": [], "min_value": 1, "max_value": 10, "step": 2, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_1", "default": null, "conditions": [], "min_value": 1, "max_value": 10, "step": 2, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_2", "default": null, "conditions": [], "min_value": 1, "max_value": 10, "step": 2, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_3", "default": null, "conditions": [], "min_value": 1, "max_value": 10, "step": 2, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_4", "default": null, "conditions": [], "min_value": 1, "max_value": 10, "step": 2, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_5", "default": null, "conditions": [], "min_value": 1, "max_value": 10, "step": 2, "sampling": "linear"}}], "values": {"activation": "sigmoid", "first_units": 1, "num_layers": 1, "units_0": 1, "units_1": 9, "units_2": 5, "units_3": 1, "units_4": 1, "units_5": 3, "tuner/epochs": 7, "tuner/initial_epoch": 0, "tuner/bracket": 1, "tuner/round": 0}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/opt/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/layers/layer.py\", line 230, in build_wrapper\n    original_build_method(*args, **kwargs)\n  File \"/opt/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/models/sequential.py\", line 195, in build\n    x = layer(x)\n  File \"/opt/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 122, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/opt/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/backend/common/name_scope.py\", line 61, in __exit__\n    name_scope_stack.pop()\nIndexError: pop from empty list\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/opt/anaconda3/envs/dev/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/opt/anaconda3/envs/dev/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"/opt/anaconda3/envs/dev/lib/python3.10/site-packages/keras_tuner/src/tuners/hyperband.py\", line 427, in run_trial\n    return super().run_trial(trial, *fit_args, **fit_kwargs)\n  File \"/opt/anaconda3/envs/dev/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"/opt/anaconda3/envs/dev/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 232, in _build_and_fit_model\n    model = self._try_build(hp)\n  File \"/opt/anaconda3/envs/dev/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 164, in _try_build\n    model = self._build_hypermodel(hp)\n  File \"/opt/anaconda3/envs/dev/lib/python3.10/site-packages/keras_tuner/src/tuners/hyperband.py\", line 430, in _build_hypermodel\n    model = super()._build_hypermodel(hp)\n  File \"/opt/anaconda3/envs/dev/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 155, in _build_hypermodel\n    model = self.hypermodel.build(hp)\n  File \"/Users/ilangoldstein/cubc/project4/app.py\", line 52, in create_model\n    model.add(tf.keras.layers.Dense(\n  File \"/opt/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/models/sequential.py\", line 122, in add\n    self._maybe_rebuild()\n  File \"/opt/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/models/sequential.py\", line 149, in _maybe_rebuild\n    self.build(input_shape)\n  File \"/opt/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/layers/layer.py\", line 228, in build_wrapper\n    with obj._open_name_scope():\n  File \"/opt/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/backend/tensorflow/core.py\", line 679, in __exit__\n    super().__exit__(*args, **kwargs)\n  File \"/opt/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/backend/common/name_scope.py\", line 61, in __exit__\n    name_scope_stack.pop()\nIndexError: pop from empty list\n"}